### ISSUE TITLE
Could not resolve all files for configuration

### ISSUE THREAD

**Issue by Ternowy** [Richou/react-native-android-location-enabler#16]
**Console now, i'm trying just run android**
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

**Bahaviour**
3 days before everything worked perfect, now we have such problem

**Comment by khjde1207** [comment]
Change the order.
```
allprojects {
    repositories {
        mavenLocal() 
        google() //***************1
        jcenter() //***************2
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        

    }


}
```

**Comment by Richou** [comment]
I think, I must update some code, I'll do it asap.

**Comment by Ternowy** [comment]
> Change the order.
> 
> ```
> allprojects {
>     repositories {
>         mavenLocal() 
>         google() //***************1
>         jcenter() //***************2
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>         
> 
>     }
> 
> 
> }
> ```

This solved my trouble
