### ISSUE TITLE
Outdated repositories (jcenter)

### ISSUE THREAD

**Issue by MateRyze** [Richou/react-native-android-location-enabler#19]
Getting this error message, when trying to run it:
> A problem occurred configuring project ':react-native-android-location-enabler'.
> Could not resolve all files for configuration ':react-native-android-location-enabler:classpath'.
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.1.0-alpha01).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/manifest-merger/26.1.0/manifest-merger-26.1.0.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.1.0/ddmlib-26.1.0.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/dvlib/26.1.0/dvlib-26.1.0.jar
   > Could not find common.jar (com.android.tools:common:26.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/26.1.0/common-26.1.0.jar
   > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0.jar

**Comment by Peretz30** [comment]
Had this issue too, #20 did the trick

**Comment by Richou** [comment]
Fixed release will be available soon.
Sorry for the late.

**Comment by Richou** [comment]
v1.0.9 has been released, thx for the PR.
