### ISSUE TITLE
Support React-native 0.60 and AndroidX

### ISSUE THREAD

**Issue by MBach** [Richou/react-native-android-location-enabler#24]
Hello,

New release of React-native https://facebook.github.io/react-native/blog/2019/07/03/version-60 has changed on how dependencies should be linked.

Regards,

**Comment by Richou** [comment]
Hello,
Thanks for the issue, I release v1.2.0, can you tell me if it is good for you ?

Regards.

**Comment by MBach** [comment]
Working perfectly!

**Comment by Adibacaj** [comment]
> Hello,
> Thanks for the issue, I release v1.2.0, can you tell me if it is good for you ?
> 
> Regards.

@Richou can you see this issue? 
https://github.com/Richou/react-native-android-location-enabler/issues/29

I have this problem when I upgraded to react-native 0.61

**Comment by Jojr** [comment]
@Adibacaj I'm facing the same issue in RN 61.5.

Have you solved this issue?

**Comment by singhvishal802** [comment]
Try adding following dependency under app/build.gradle
implementation 'com.google.android.gms:play-services-location:15.0.0'
Make sure to change all the play services dependency to same version.

**Comment by Jojr** [comment]
@singhvishal802  thank you for your advice.
I changed my code to another approach using **PermissionsAndroid** from RN core.

If anyone want to know about it:
https://facebook.github.io/react-native/docs/permissionsandroid
