### ISSUE TITLE
Screenshots Please

### ISSUE THREAD

**Issue by Noitidart** [Richou/react-native-android-location-enabler#4]
May you please add screenshots (ideally GIF) of this in action in repo? That's the first thing a lot of RN package searchers do. There are so many packages its not easy to install each one (this one especially as it requires native linking), render it respecting properties, then uninstall it if it doesn't fit.

**Comment by Richou** [comment]
Ok no problem, I will add screenshots asap.

**Comment by Noitidart** [comment]
Thank you @Richou  !!

**Comment by Richou** [comment]
@Noitidart I added a Gif to show the component in action. Is it good for you ?
Regards.

**Comment by Noitidart** [comment]
Oh wow so great!! Thank you @Richou ! Thanks also for leaving open for me to close. Such a great module!
