### ISSUE TITLE
Feat: turn off GPS

### ISSUE THREAD

**Issue by sshanzel** [Richou/react-native-android-location-enabler#41]
This sounds a bit weird,but is it possible to actually turn the GPS off by a trigger? Lol

**Comment by Richou** [comment]
Sorry, but I don't think that is possible. :/

**Comment by sshanzel** [comment]
Yeah, it was funny that people think since you turned it off, you'll have the capacity to turn it off. It sounds logical but why not just hit the location in the status bar. Lol
