### ISSUE TITLE
Possible to explain why we need location in the prompt?

### ISSUE THREAD

**Issue by Noitidart** [Richou/react-native-android-location-enabler#5]
Is it possible to explain why we need location access in the prompt? Or for this would i need to roll my own dialog, and then use some native module to enable location services for my app. (is it possible to auto enable location services for my app, as this dialog does?)

**Comment by Richou** [comment]
The prompt is displayed by Google Location Services API, I don't think there is a way to add a custom explanation. You will have to add a layer or dialog to explain why you need the access to user location.
And in my opinion, for user experience, it is better to ask him permission before activate location services.

**Comment by Noitidart** [comment]
Darn. I was hoping we can just add a few words to that message like ios does. It shows the default message follwoed by custom message.

No worries, thanks for this awesome module!

**Comment by Richou** [comment]
Thanks. :)
