### ISSUE TITLE
I have Problem in android 12

### ISSUE THREAD

**Issue by zabipakdel** [Richou/react-native-android-location-enabler#70]
I have Problem in android 12
permission will granted but will crash after that

**Comment by vatsal-gadhiya-searce** [comment]
@Richou I have the same issue in android 11 as well. Any update?

**Comment by zabipakdel** [comment]
I found the solution 
https://github.com/rnmapbox/maps/issues/1286#issuecomment-805167752

**Comment by CptFabulouso** [comment]
So it was error in mapbox and not this lib? Or did you take something from that solution and applied patch for this lib?

**Comment by zabipakdel** [comment]
I just add this lines of code and works fine

 It was fixed in mapbox several months ago but has not been updated in this library. A workaround is to add this line:
implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'
to the @react-native-mapbox-gl/maps/android/rctmgl/build.gradle file under the
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0
line.

**Comment by CptFabulouso** [comment]
ok, so it's mapbox issue, because it says to modify `@react-native-mapbox-gl/maps/android/rctmgl/build.gradle` file, for which you have to have that lib installed, it's not dependency of this lib. Thank you

**Comment by zabipakdel** [comment]
your welcome
