### ISSUE TITLE
Promise not working

### ISSUE THREAD

**Issue by vink1987** [Richou/react-native-android-location-enabler#8]
When the gps is turned off and we open the app, I call promptForEnableLocationIfNeeded method which asks the user to enable location with Ok and Cancel buttons. When user selects Ok or Cancel, the promise doesn't work in react-native code. Please update the code.

**Comment by Richou** [comment]
I've tried your case and that worked for me as you can see on the gif bellow:

![promise-working](https://user-images.githubusercontent.com/6146736/40231794-b649425a-5a9c-11e8-8dc7-48e1fe5b1a4c.gif)

The code I used :

```javascript
export default class App extends Component<{}> {

  componentDidMount = () => {
    this.onLocationEnable();
  }

  onLocationEnable = () => {
    RNAndroidLocationEnabler.promptForEnableLocationIfNeeded({interval: 10000, fastInterval: 5000})
      .then(data => {
        alert(data);
      }).catch(err => {
        alert("Error " + err.message + ", Code : " + err.code);
      });
  }
}
```

**Comment by koo27** [comment]
Actually it's not working for the catch promise

**Comment by gabrielgreghi** [comment]
Eu tive o mesmo problema =( , as vezes, mesmo quando o usuário pressionando no OK, o promisse cai no catch. =(
