### ISSUE TITLE
Incompatibility Issue with turbo-darwin-64@1.10.14 on arm64 CPU Architecture

### ISSUE THREAD

**Issue by chlee1001** [Richou/react-native-android-location-enabler#95]
### Problem Description

During the execution of the yarn install command, an error occurs indicating that the turbo-darwin-64@1.10.14 package is not compatible with the arm64 CPU architecture.
How can I solve this?

### Logs

```bash
 yarn install
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning react-native-android-location-enabler > vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
warning react-native-android-location-enabler > degenerator > vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
[3/5] 🚚  Fetching packages...
error turbo-darwin-64@1.10.14: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

### Version
- react-native : 0.72.4
- "react-native-android-location-enabler : 2.0.0

### Additional Information
Apple M1 Pro  - macOS Ventura 13.5.2
Yarn Version: v1.22.19

**Comment by Richou** [comment]
Oh, didn't see that coming, I'll check asap.

**Comment by Richou** [comment]
I just released a new version `2.0.1` can you try with this version please ?

**Comment by chlee1001** [comment]
@Richou 
It will now install well.
Thank you for your quick action.

**Comment by Richou** [comment]
@chlee1001 It still does not work ?

**Comment by chlee1001** [comment]
@Richou 
It works fine.
Thank you 👍
