### ISSUE TITLE
could not invoke RNAndroidLocationEnabler.promptForEnableLocationIfNeeded. found interface com.google.android.gms.location.settingsclient, but class was expected

### ISSUE THREAD

**Issue by JeanMarieK** [Richou/react-native-android-location-enabler#99]
I'm getting this error on my physical device screen after running the app: could not invoke RNAndroidLocationEnabler.promptForEnableLocationIfNeeded. found interface com.google.android.gms.location.settingsclient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in /data/app/~~dQIJYPyV_0zb5PG-2RsSMg==/applicationId-s0 mk9yoRtp0KWm9j-w-wQ==/ base.apk)

![276382056-3ee16be4-e31f-4a78-9f54-dd7ab937cb82](https://github.com/Richou/react-native-android-location-enabler/assets/43825319/03410c0d-0f28-4bfe-944a-495346826cfc)

react-native version 0.66.4
"react-native-android-location-enabler": "^1.2.2"

**Comment by Richou** [comment]
Can you try this https://github.com/Baseflow/flutter-geolocator/issues/1214#issuecomment-1419562502 ? The comment was for a flutter project but maybe it will work for your issue.

**Comment by JeanMarieK** [comment]
> Can you try this [Baseflow/flutter-geolocator#1214 (comment)](https://github.com/Baseflow/flutter-geolocator/issues/1214#issuecomment-1419562502) ? The comment was for a flutter project but maybe it will work for your issue.

It worked. I only added "force "com.google.android.gms:play-services-location:21.0.1" in resolutionStrategy {}. Thanks a lot!

**Comment by ksd711** [comment]
> Can you try this [Baseflow/flutter-geolocator#1214 (comment)](https://github.com/Baseflow/flutter-geolocator/issues/1214#issuecomment-1419562502) ? The comment was for a flutter project but maybe it will work for your issue.

this work for me
